services:
  - type: web
    name: flynjet
    runtime: image
    repo: https://github.com/ngirita/flynjet
    branch: main
    dockerfilePath: ./Dockerfile
    buildArgs:
      - key: DATABASE_URL
        fromDatabase:
          name: flynjet-db
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flynjet-db
      - key: DEBUG
        value: false
      - key: SITE_URL
        value: https://flynjet.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false