services:
  - type: web
    name: flynjet
    runtime: image
    repo: https://github.com/ngirita/flynjet
    branch: main
    dockerfilePath: ./Dockerfile
    buildArgs:
      - key: DATABASE_URL
        value: postgresql://flynjet_db_user:T7tSdJ0A41atTJuZa5hyUn2J4Gwh56Jf@dpg-d776hpma2pns7392sn40-a:5432/flynjet_db?sslmode=require
    envVars:
      - key: DEBUG
        value: false
      - key: SITE_URL
        value: https://flynjet.com
      - key: DATABASE_URL
        value: postgresql://flynjet_db_user:T7tSdJ0A41atTJuZa5hyUn2J4Gwh56Jf@dpg-d776hpma2pns7392sn40-a:5432/flynjet_db?sslmode=require