# Generated by Django 5.2.12 on 2026-03-31 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('integration_type', models.CharField(choices=[('weather', 'Weather Service'), ('flight_data', 'Flight Data'), ('fuel_prices', 'Fuel Prices'), ('currency', 'Currency Exchange'), ('payment', 'Payment Gateway'), ('email', 'Email Service'), ('sms', 'SMS Service'), ('maps', 'Maps Service'), ('insurance', 'Insurance API'), ('customs', 'Customs API')], max_length=20)),
                ('base_url', models.URLField()),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth 2.0'), ('basic', 'Basic Auth'), ('jwt', 'JWT'), ('none', 'No Auth')], max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('client_id', models.CharField(blank=True, max_length=500)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('rate_limit', models.IntegerField(default=0, help_text='Requests per minute, 0 for unlimited')),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['integration_type'], name='integration_integra_9e52ba_idx'), models.Index(fields=['is_active'], name='integration_is_acti_5058dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='integration_expires_5b9924_idx')],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='FuelPriceCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_code', models.CharField(db_index=True, max_length=10)),
                ('jet_a_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avgas_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['location_code'], name='integration_locatio_bf20b8_idx'), models.Index(fields=['expires_at'], name='integration_expires_0c0b22_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_key', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.IntegerField()),
                ('conditions', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('forecast', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['location_key'], name='integration_locatio_0f65e8_idx'), models.Index(fields=['expires_at'], name='integration_expires_b322df_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200, unique=True)),
                ('secret', models.CharField(max_length=100)),
                ('events', models.JSONField(default=list)),
                ('handler_function', models.CharField(max_length=200)),
                ('allowed_ips', models.JSONField(default=list)),
                ('require_signature', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['path'], name='integration_path_58b251_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='integration_status_d14ae6_idx'), models.Index(fields=['event_type'], name='integration_event_t_0c65d6_idx')],
            },
        ),
    ]
