# Generated by Django 5.2.12 on 2026-03-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_testimonial_user_alter_testimonial_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking Update'), ('payment', 'Payment Update'), ('flight', 'Flight Status'), ('promotion', 'Promotion'), ('system', 'System Message'), ('security', 'Security Alert'), ('reminder', 'Reminder'), ('chat', 'Chat Message')], max_length=20),
        ),
    ]
