# Generated by Django 5.2.12 on 2026-03-27 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('enquiry', '📋 New Enquiry'), ('payment', '💰 New Payment'), ('booking', '✈️ New Booking'), ('contract', '📄 Contract Update'), ('system', '⚙️ System Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='core_adminn_is_read_11f2db_idx'), models.Index(fields=['notification_type'], name='core_adminn_notific_f10ceb_idx')],
            },
        ),
    ]
