# Generated by Django 5.2.12 on 2026-03-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='+447393700477', max_length=20, verbose_name='WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_phone',
            field=models.CharField(default='+254785651832', max_length=20),
        ),
    ]
