# Generated by Django 5.2.12 on 2026-03-31 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(blank=True, help_text='Routing/ABA number', max_length=50)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=20)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('branch_address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('phone', 'Phone Number'), ('whatsapp', 'WhatsApp Number'), ('email', 'Email Address'), ('emergency', 'Emergency Contact')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, help_text="e.g., 'Sales', 'Support'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Contact',
                'verbose_name_plural': 'Company Contacts',
                'ordering': ['contact_type', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('working_hours', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Office Location',
                'verbose_name_plural': 'Office Locations',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_key', models.CharField(choices=[('paystack', 'Paystack (Cards)'), ('bank_transfer', 'Bank Transfer'), ('wire_transfer', 'Wire Transfer'), ('crypto_all', 'Cryptocurrency (All)'), ('usdt_erc20', 'USDT (ERC-20)'), ('usdt_trc20', 'USDT (TRC-20)'), ('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-credit-card', max_length=50)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable this payment method')),
                ('is_visible', models.BooleanField(default=True, help_text='Show on checkout page')),
                ('is_maintenance', models.BooleanField(default=False, help_text='Under maintenance mode')),
                ('maintenance_message', models.CharField(blank=True, default='This payment method is currently under maintenance. Please use another payment method.', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method Config',
                'verbose_name_plural': 'Payment Method Configs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crypto_type', models.CharField(choices=[('usdt', 'USDT'), ('usdc', 'USDC'), ('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('sol', 'Solana'), ('bnb', 'BNB')], max_length=20)),
                ('network', models.CharField(choices=[('erc20', 'ERC-20 (Ethereum)'), ('trc20', 'TRC-20 (Tron)'), ('bep20', 'BEP-20 (Binance Smart Chain)'), ('solana', 'Solana'), ('bitcoin', 'Bitcoin (Native)'), ('lightning', 'Lightning Network')], max_length=20)),
                ('wallet_address', models.CharField(max_length=200)),
                ('wallet_name', models.CharField(blank=True, help_text='Label for this wallet', max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='crypto_qr/')),
                ('min_deposit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('max_deposit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crypto Wallet',
                'verbose_name_plural': 'Crypto Wallets',
                'ordering': ['sort_order'],
                'unique_together': {('crypto_type', 'network')},
            },
        ),
    ]
