# Generated by Django 5.2.12 on 2026-03-31 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bankdetail_companycontact_officelocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('github', 'GitHub'), ('reddit', 'Reddit'), ('tumblr', 'Tumblr'), ('wechat', 'WeChat'), ('line', 'Line'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('medium', 'Medium'), ('patreon', 'Patreon'), ('custom', 'Custom Platform')], max_length=50)),
                ('url', models.URLField(help_text='Full URL to your profile/page', max_length=500)),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fab fa-facebook')", max_length=100)),
                ('custom_name', models.CharField(blank=True, help_text="Custom name if platform is 'custom'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['sort_order'],
            },
        ),
    ]
