# Generated by Django 5.2.12 on 2026-03-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='link_text',
            field=models.CharField(blank=True, help_text="Link text (e.g., 'View on Explorer', 'Buy USDT')", max_length=100),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional link (e.g., blockchain explorer, exchange link)', max_length=500),
        ),
    ]
