# Generated by Django 5.2.12 on 2026-04-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cryptowallet_link_text_cryptowallet_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='source_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='link',
            field=models.CharField(blank=True, help_text='URL to navigate when clicked', max_length=500),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('enquiry', 'New Enquiry'), ('payment', 'New Payment'), ('booking', 'New Booking'), ('contract', 'Contract Update'), ('system', 'System Alert'), ('dispute', 'New Dispute'), ('support', 'New Support Ticket'), ('review', 'New Review')], max_length=20),
        ),
    ]
