# Generated by Django 5.2.12 on 2026-03-22 00:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('ticket', 'E-Ticket'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('insurance', 'Insurance Certificate'), ('customs', 'Customs Form'), ('boarding_pass', 'Boarding Pass')], max_length=20)),
                ('template_file', models.FileField(upload_to='document_templates/', validators=[django.core.validators.FileExtensionValidator(['html', 'pdf', 'docx'])])),
                ('variables', models.JSONField(default=list, help_text='List of available variables')),
                ('styles', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('document_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('ticket', 'E-Ticket'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('insurance', 'Insurance Certificate'), ('customs', 'Customs Form'), ('boarding_pass', 'Boarding Pass')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('html_file', models.FileField(blank=True, upload_to='documents/html/%Y/%m/%d/')),
                ('file_size', models.IntegerField(default=0)),
                ('content_data', models.JSONField(default=dict, help_text='Data used to generate document')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_password', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('expired', 'Expired')], default='generated', max_length=20)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bookings.booking')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bookings.invoice')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSigning',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signer_name', models.CharField(max_length=200)),
                ('signing_method', models.CharField(choices=[('electronic', 'Electronic Signature'), ('digital', 'Digital Certificate'), ('biometric', 'Biometric'), ('sms', 'SMS Verification'), ('email', 'Email Verification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature image')),
                ('signature_hash', models.CharField(blank=True, max_length=128)),
                ('certificate_info', models.JSONField(blank=True, default=dict)),
                ('verification_code', models.CharField(blank=True, max_length=10)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_signatures', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.generateddocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archive_reference', models.CharField(max_length=100, unique=True)),
                ('archive_date', models.DateTimeField(auto_now_add=True)),
                ('archive_reason', models.CharField(max_length=200)),
                ('archived_file', models.FileField(upload_to='archives/%Y/%m/')),
                ('file_hash', models.CharField(max_length=128)),
                ('file_size', models.IntegerField()),
                ('retention_until', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('original_document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.generateddocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['document_number'], name='documents_g_documen_b8e18b_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['user', '-created_at'], name='documents_g_user_id_592871_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['booking', 'document_type'], name='documents_g_booking_2b5c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['access_token'], name='documents_g_access__4a5311_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['expires_at'], name='documents_g_expires_dfdbda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentsigning',
            unique_together={('document', 'signer')},
        ),
        migrations.AddIndex(
            model_name='documentarchive',
            index=models.Index(fields=['archive_reference'], name='documents_d_archive_ac1dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentarchive',
            index=models.Index(fields=['retention_until'], name='documents_d_retenti_4e8960_idx'),
        ),
    ]
