# Generated by Django 5.2.12 on 2026-03-31 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreachNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breach_number', models.CharField(max_length=50, unique=True)),
                ('detected_at', models.DateTimeField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('notified', 'Notified'), ('resolved', 'Resolved')], default='detected', max_length=20)),
                ('description', models.TextField()),
                ('affected_data', models.JSONField(default=list)),
                ('affected_users_count', models.IntegerField(default=0)),
                ('root_cause', models.TextField(blank=True)),
                ('impact_assessment', models.TextField(blank=True)),
                ('notified_authorities', models.BooleanField(default=False)),
                ('authorities_notified_at', models.DateTimeField(blank=True, null=True)),
                ('notified_users', models.BooleanField(default=False)),
                ('users_notified_at', models.DateTimeField(blank=True, null=True)),
                ('remediation_steps', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['breach_number'], name='compliance__breach__f10bb4_idx'), models.Index(fields=['status'], name='compliance__status_6e0896_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataProcessingAgreement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_number', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('agreement_type', models.CharField(choices=[('processor', 'Data Processor'), ('controller', 'Data Controller'), ('subprocessor', 'Sub-processor')], max_length=20)),
                ('purpose', models.TextField()),
                ('data_categories', models.JSONField(default=list)),
                ('signed_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('security_measures', models.TextField()),
                ('breach_notification_time', models.IntegerField(help_text='Hours to notify of breach')),
                ('agreement_file', models.FileField(upload_to='compliance/dpa/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['agreement_number'], name='compliance__agreeme_f4080d_idx'), models.Index(fields=['expiry_date'], name='compliance__expiry__43d66b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('marketing', 'Marketing Communications'), ('cookies', 'Cookie Consent'), ('data_processing', 'Data Processing'), ('third_party', 'Third Party Sharing')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('granted', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('document_url', models.URLField(blank=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consent_type'], name='compliance__user_id_130759_idx'), models.Index(fields=['-created_at'], name='compliance__created_b4fc34_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_name', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('access', 'Right to Access'), ('rectification', 'Right to Rectification'), ('erasure', 'Right to Erasure'), ('restriction', 'Right to Restriction'), ('portability', 'Right to Data Portability'), ('objection', 'Right to Object')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('description', models.TextField()),
                ('verification_method', models.CharField(max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_file', models.FileField(blank=True, upload_to='compliance/dsr/%Y/%m/')),
                ('response_notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['request_number'], name='compliance__request_96510d_idx'), models.Index(fields=['status', 'deadline'], name='compliance__status_93d4fb_idx')],
            },
        ),
    ]
