# Generated by Django 5.2.12 on 2026-03-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card (Visa/Mastercard via Paystack)'), ('crypto', 'Cryptocurrency (BTC / USDT)'), ('usdt_erc20', 'USDT (ERC-20)'), ('usdt_trc20', 'USDT (TRC-20)'), ('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('bank_transfer', 'Bank Transfer'), ('wire_transfer', 'Wire Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Card (Visa/Mastercard via Paystack)'), ('crypto', 'Cryptocurrency (BTC / USDT)'), ('usdt_erc20', 'USDT (ERC-20)'), ('usdt_trc20', 'USDT (TRC-20)'), ('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('bank_transfer', 'Bank Transfer'), ('wire_transfer', 'Wire Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_method',
            field=models.CharField(choices=[('card', 'Card (Visa/Mastercard via Paystack)'), ('crypto', 'Cryptocurrency (BTC / USDT)'), ('usdt_erc20', 'USDT (ERC-20)'), ('usdt_trc20', 'USDT (TRC-20)'), ('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('bank_transfer', 'Bank Transfer'), ('wire_transfer', 'Wire Transfer')], max_length=20),
        ),
    ]
