# Generated by Django 5.2.12 on 2026-03-20 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('points', 'Points Based'), ('tier', 'Tier Based'), ('hybrid', 'Hybrid')], max_length=20)),
                ('points_per_dollar', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('minimum_points_redemption', models.IntegerField(default=1000)),
                ('tiers', models.JSONField(default=list, help_text='List of tiers and benefits')),
                ('benefits', models.JSONField(default=list)),
                ('enrollment_rules', models.TextField(blank=True)),
                ('earning_rules', models.TextField(blank=True)),
                ('redemption_rules', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('points_balance', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('current_tier', models.CharField(default='bronze', max_length=50)),
                ('tier_progress', models.IntegerField(default=0, help_text='Progress to next tier')),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketing.loyaltyprogram')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Points Earned'), ('redeem', 'Points Redeemed'), ('expire', 'Points Expired'), ('adjust', 'Manual Adjustment'), ('bonus', 'Bonus Points')], max_length=20)),
                ('points', models.IntegerField()),
                ('source', models.CharField(choices=[('booking', 'Flight Booking'), ('referral', 'Referral'), ('promotion', 'Promotion'), ('tier_upgrade', 'Tier Upgrade'), ('feedback', 'Feedback'), ('review', 'Review'), ('social', 'Social Media')], max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketing.loyaltyaccount')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promotion_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('promotion_type', models.CharField(choices=[('discount', 'Discount'), ('points_multiplier', 'Points Multiplier'), ('bonus_points', 'Bonus Points'), ('upgrade', 'Free Upgrade'), ('gift', 'Gift')], max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('points_multiplier', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('bonus_points', models.IntegerField(blank=True, null=True)),
                ('min_booking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_passengers', models.IntegerField(blank=True, null=True)),
                ('applicable_aircraft', models.JSONField(blank=True, default=list)),
                ('applicable_routes', models.JSONField(blank=True, default=list)),
                ('user_segments', models.JSONField(blank=True, default=list)),
                ('max_uses_total', models.IntegerField(default=0, help_text='0 for unlimited')),
                ('max_uses_per_user', models.IntegerField(default=1)),
                ('current_uses', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['promotion_code'], name='marketing_p_promoti_9ed3e3_idx'), models.Index(fields=['start_date', 'end_date'], name='marketing_p_start_d_71456f_idx'), models.Index(fields=['is_active'], name='marketing_p_is_acti_98e1a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='marketing.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referred_email', models.EmailField(max_length=254)),
                ('referral_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('referrer_reward', models.IntegerField(default=0, help_text='Points awarded to referrer')),
                ('referred_reward', models.IntegerField(default=0, help_text='Points awarded to referred user')),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('signed_up_at', models.DateTimeField(blank=True, null=True)),
                ('first_booking_at', models.DateTimeField(blank=True, null=True)),
                ('reward_issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('email', 'Email Campaign'), ('sms', 'SMS Campaign'), ('push', 'Push Notification'), ('social', 'Social Media'), ('display', 'Display Ad'), ('referral', 'Referral Program'), ('loyalty', 'Loyalty Program')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('target_audience', models.JSONField(default=dict, help_text='Targeting criteria')),
                ('segment_size', models.IntegerField(default=0)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('template', models.CharField(blank=True, max_length=200)),
                ('images', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('converted_count', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_ab_test', models.BooleanField(default=False)),
                ('variant_a', models.JSONField(blank=True, default=dict)),
                ('variant_b', models.JSONField(blank=True, default=dict)),
                ('winning_variant', models.CharField(blank=True, max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign_number'], name='marketing_c_campaig_4ceace_idx'), models.Index(fields=['status', 'start_date'], name='marketing_c_status_221ab7_idx'), models.Index(fields=['campaign_type'], name='marketing_c_campaig_94ec94_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['account_number'], name='marketing_l_account_9f83c5_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['user'], name='marketing_l_user_id_a85636_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['current_tier'], name='marketing_l_current_20a9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['account', '-created_at'], name='marketing_l_account_0ddecb_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['transaction_type'], name='marketing_l_transac_216d32_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['promotion', 'user'], name='marketing_p_promoti_ccbbdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionusage',
            unique_together={('promotion', 'user', 'booking')},
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code'], name='marketing_r_referra_5a5e26_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='marketing_r_referre_4293c6_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_email'], name='marketing_r_referre_e541ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referrer', 'referred_email')},
        ),
    ]
