# Generated by Django 5.2.12 on 2026-03-27 02:55

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(db_index=True, help_text='3-letter IATA airport code (e.g., JFK, LHR)', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'IATA code must be 3 uppercase letters.')])),
                ('icao_code', models.CharField(blank=True, db_index=True, max_length=4)),
                ('name', models.CharField(help_text='Full airport name', max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('elevation_ft', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['iata_code'], name='airports_ai_iata_co_ea5b11_idx'), models.Index(fields=['city', 'country'], name='airports_ai_city_91d298_idx'), models.Index(fields=['name'], name='airports_ai_name_b30727_idx')],
            },
        ),
    ]
