# Generated by Django 5.2.12 on 2026-03-30 00:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0009_contractlineitem'),
        ('payments', '0003_alter_payment_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('dispute_type', models.CharField(choices=[('cancellation', 'Cancellation Dispute'), ('refund', 'Refund Dispute'), ('chargeback', 'Chargeback'), ('service', 'Service Quality'), ('billing', 'Billing Error'), ('damage', 'Damage Claim'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('disputed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('response_deadline', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('refund_issued', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_transaction_id', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='bookings.booking')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='payments.payment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-filed_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_disputes', models.IntegerField(default=0)),
                ('open_disputes', models.IntegerField(default=0)),
                ('resolved_disputes', models.IntegerField(default=0)),
                ('escalated_disputes', models.IntegerField(default=0)),
                ('total_disputed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_resolution_time_hours', models.FloatField(default=0)),
                ('customer_satisfaction_rate', models.FloatField(default=0)),
                ('disputes_by_type', models.JSONField(default=dict)),
                ('disputes_by_status', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('communication', 'Communication'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='dispute_evidence/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='disputes.dispute')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='dispute_attachments/%Y/%m/%d/')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResolution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_type', models.CharField(choices=[('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('credit', 'Future Credit'), ('rebooking', 'Free Rebooking'), ('upgrade', 'Complimentary Upgrade'), ('apology', 'Formal Apology'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_expiry', models.DateTimeField(blank=True, null=True)),
                ('accepted_by_customer', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='disputes.dispute')),
                ('new_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolution', to='bookings.booking')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['dispute_number'], name='disputes_di_dispute_c1ecdf_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['user', '-filed_at'], name='disputes_di_user_id_e74b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['booking'], name='disputes_di_booking_48b976_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'priority'], name='disputes_di_status_3dbe35_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['assigned_to', 'status'], name='disputes_di_assigne_eb5d18_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeresolution',
            index=models.Index(fields=['dispute', 'accepted_by_customer'], name='disputes_di_dispute_d7c59c_idx'),
        ),
    ]
