# Generated by Django 5.2.12 on 2026-03-25 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightTrack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(db_index=True, max_length=20)),
                ('aircraft_registration', models.CharField(max_length=20)),
                ('airline', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in feet', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Ground speed in knots', null=True)),
                ('vertical_speed', models.FloatField(blank=True, help_text='Vertical speed in feet/min', null=True)),
                ('is_tracking', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('next_update_expected', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_air', 'In Air'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('diverted', 'Diverted'), ('landed', 'Landed')], default='scheduled', max_length=20)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('cargo_status', models.CharField(choices=[('pending', 'Pending'), ('loaded', 'Loaded'), ('in_transit', 'In Transit'), ('unloaded', 'Unloaded'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('cargo_manifest', models.JSONField(blank=True, default=list)),
                ('cargo_weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('distance_remaining', models.FloatField(blank=True, help_text='Distance in nautical miles', null=True)),
                ('time_remaining', models.DurationField(blank=True, null=True)),
                ('departure_airport', models.CharField(max_length=3)),
                ('arrival_airport', models.CharField(max_length=3)),
                ('departure_airport_name', models.CharField(blank=True, max_length=100)),
                ('arrival_airport_name', models.CharField(blank=True, max_length=100)),
                ('route', models.JSONField(blank=True, default=list, help_text='List of waypoints')),
                ('alternate_airports', models.JSONField(blank=True, default=list)),
                ('weather', models.JSONField(blank=True, default=dict)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('share_expiry', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.CharField(choices=[('manual', 'Manual Input'), ('adsb', 'ADS-B'), ('flightradar', 'FlightRadar24'), ('gps', 'GPS Device'), ('api', 'External API'), ('simulated', 'Simulated')], default='manual', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('takeoff', 'Takeoff'), ('landing', 'Landing'), ('waypoint', 'Waypoint Passed'), ('altitude', 'Altitude Change'), ('speed', 'Speed Change'), ('delay', 'Delay'), ('custom', 'Custom')], max_length=20)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('custom_message', models.CharField(blank=True, max_length=200)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=False)),
                ('notify_sms', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_alerts', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracking.flighttrack')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('departure', 'Flight Departed'), ('arrival', 'Flight Arrived'), ('delay', 'Flight Delayed'), ('position', 'Position Update'), ('weather', 'Weather Alert'), ('altitude', 'Altitude Change'), ('speed', 'Speed Change')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tracking.flighttrack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='tracking.flighttrack')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrackingShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('max_views', models.IntegerField(default=0, help_text='0 for unlimited')),
                ('views', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tracking.flighttrack')),
            ],
        ),
        migrations.AddIndex(
            model_name='flighttrack',
            index=models.Index(fields=['flight_number'], name='tracking_fl_flight__d13eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='flighttrack',
            index=models.Index(fields=['booking', 'is_tracking'], name='tracking_fl_booking_3755fe_idx'),
        ),
        migrations.AddIndex(
            model_name='flighttrack',
            index=models.Index(fields=['last_update'], name='tracking_fl_last_up_8d6775_idx'),
        ),
        migrations.AddIndex(
            model_name='flighttrack',
            index=models.Index(fields=['share_token'], name='tracking_fl_share_t_001d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='flighttrack',
            index=models.Index(fields=['status'], name='tracking_fl_status_085ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='flighttrack',
            index=models.Index(fields=['cargo_status'], name='tracking_fl_cargo_s_049acb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flightalert',
            unique_together={('track', 'user', 'alert_type')},
        ),
        migrations.AddIndex(
            model_name='trackingposition',
            index=models.Index(fields=['track', 'timestamp'], name='tracking_tr_track_i_388a67_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingshare',
            index=models.Index(fields=['token'], name='tracking_tr_token_864540_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingshare',
            index=models.Index(fields=['expires_at'], name='tracking_tr_expires_40c3b1_idx'),
        ),
    ]
