# Generated by Django 5.2.12 on 2026-03-27 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('fleet', '0002_enquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('departure_airport', models.CharField(max_length=3)),
                ('arrival_airport', models.CharField(max_length=3)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('passenger_count', models.IntegerField()),
                ('luggage_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_surcharge_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('handling_fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('catering_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('terms_conditions', models.TextField(default='Standard terms and conditions apply...')),
                ('valid_until', models.DateTimeField()),
                ('special_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('viewed', 'Viewed by Client'), ('accepted', 'Accepted'), ('payment_initiated', 'Payment Initiated'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_link', models.URLField(blank=True)),
                ('payment_link_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('payment_link_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.aircraft')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='bookings.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='fleet.enquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
