# Generated by Django 5.2.12 on 2026-03-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='send_count',
            field=models.IntegerField(default=0),
        ),
    ]
