# Generated by Django 5.2.12 on 2026-03-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_contract_pdf_file_contract_send_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='admin_signature',
            field=models.TextField(blank=True, help_text='Admin signature text or name'),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='admin_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of amenities. Format: [{"name": "Amenity", "details": "Details"}]'),
        ),
        migrations.AddField(
            model_name='contract',
            name='exclusions',
            field=models.JSONField(blank=True, default=list, help_text='List of excluded items. Format: [{"item": "Item name", "status": "excluded", "notes": "notes"}]'),
        ),
        migrations.AddField(
            model_name='contract',
            name='inclusions',
            field=models.JSONField(blank=True, default=list, help_text='List of included items. Format: [{"item": "Item name", "status": "included", "notes": "notes"}]'),
        ),
    ]
