# Generated by Django 5.2.12 on 2026-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_contract_admin_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amenity_bedroom',
            field=models.BooleanField(default=False, verbose_name='✓ Bedroom'),
        ),
        migrations.AddField(
            model_name='contract',
            name='amenity_catering',
            field=models.BooleanField(default=True, verbose_name='✓ Catering'),
        ),
        migrations.AddField(
            model_name='contract',
            name='amenity_conference',
            field=models.BooleanField(default=False, verbose_name='✓ Conference Table'),
        ),
        migrations.AddField(
            model_name='contract',
            name='amenity_entertainment',
            field=models.BooleanField(default=True, verbose_name='✓ Entertainment System'),
        ),
        migrations.AddField(
            model_name='contract',
            name='amenity_galley',
            field=models.BooleanField(default=True, verbose_name='✓ Full Galley'),
        ),
        migrations.AddField(
            model_name='contract',
            name='amenity_lavatory',
            field=models.BooleanField(default=True, verbose_name='✓ Lavatory'),
        ),
        migrations.AddField(
            model_name='contract',
            name='amenity_shower',
            field=models.BooleanField(default=False, verbose_name='✓ Shower'),
        ),
        migrations.AddField(
            model_name='contract',
            name='amenity_wifi',
            field=models.BooleanField(default=True, verbose_name='✓ WiFi'),
        ),
        migrations.AddField(
            model_name='contract',
            name='custom_amenities_text',
            field=models.TextField(blank=True, help_text='Additional amenities (one per line)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='custom_exclusions_text',
            field=models.TextField(blank=True, help_text='Exclusions (one per line)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='custom_inclusions_text',
            field=models.TextField(blank=True, help_text='Additional inclusions (one per line)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ground_transport_included',
            field=models.BooleanField(default=False, verbose_name='✓ Ground Transportation'),
        ),
        migrations.AddField(
            model_name='contract',
            name='hotel_accommodation_included',
            field=models.BooleanField(default=False, verbose_name='✓ Hotel Accommodation'),
        ),
    ]
