# Generated by Django 5.2.12 on 2026-03-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_contract_amenity_bedroom_contract_amenity_catering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cancellation_10_6_days',
            field=models.DecimalField(decimal_places=2, default=30, help_text='% charge for 10-6 days before departure', max_digits=5, verbose_name='10-6 days penalty %'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cancellation_24_hours',
            field=models.DecimalField(decimal_places=2, default=60, help_text='% charge for 24 hours before departure', max_digits=5, verbose_name='24 hours penalty %'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cancellation_3_days',
            field=models.DecimalField(decimal_places=2, default=50, help_text='% charge for 3 days before departure', max_digits=5, verbose_name='3 days penalty %'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cancellation_5_days',
            field=models.DecimalField(decimal_places=2, default=40, help_text='% charge for 5 days before departure', max_digits=5, verbose_name='5 days penalty %'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cancellation_notes',
            field=models.TextField(blank=True, help_text='Additional cancellation terms', verbose_name='Cancellation Notes'),
        ),
    ]
