# Generated by Django 5.2.12 on 2026-03-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_contract_cancellation_10_6_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_line_items',
            field=models.JSONField(blank=True, default=list, help_text='Invoice line items. Format: [{"description": "Item", "amount": 1000.00}]'),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_notes',
            field=models.TextField(blank=True, help_text='Additional invoice notes'),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/contract/'),
        ),
    ]
