# Generated by Django 5.2.12 on 2026-03-29 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_contract_invoice_date_contract_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='bookings.contract')),
            ],
        ),
    ]
