# Generated by Django 5.2.12 on 2026-03-30 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_contractlineitem'),
        ('fleet', '0005_aircraft_average_rating_aircraft_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='fleet.aircraft'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='fleet.aircraft'),
        ),
    ]
