# Generated by Django 5.2.12 on 2026-03-21 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('returning_users', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('completed_bookings', models.IntegerField(default=0)),
                ('cancelled_bookings', models.IntegerField(default=0)),
                ('booking_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_booking_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_success', models.IntegerField(default=0)),
                ('payment_failed', models.IntegerField(default=0)),
                ('payment_method_breakdown', models.JSONField(default=dict)),
                ('flights_completed', models.IntegerField(default=0)),
                ('flight_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fleet_utilization', models.FloatField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('avg_session_duration', models.IntegerField(default=0)),
                ('support_tickets', models.IntegerField(default=0)),
                ('avg_response_time', models.IntegerField(default=0)),
                ('satisfaction_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('booking_start', 'Booking Started'), ('booking_complete', 'Booking Completed'), ('payment_start', 'Payment Started'), ('payment_complete', 'Payment Completed'), ('search', 'Search Performed'), ('login', 'User Login'), ('signup', 'User Signup'), ('logout', 'User Logout'), ('document_download', 'Document Download'), ('chat_start', 'Chat Started'), ('chat_complete', 'Chat Completed'), ('review_submit', 'Review Submitted')], max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('anonymous_id', models.CharField(blank=True, max_length=100)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_id'], name='analytics_a_event_i_92a2ea_idx'), models.Index(fields=['event_type', 'timestamp'], name='analytics_a_event_t_64745b_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_5c8c13_idx'), models.Index(fields=['session_id'], name='analytics_a_session_8757e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dashboard_type', models.CharField(choices=[('personal', 'Personal'), ('admin', 'Admin'), ('agent', 'Agent'), ('fleet', 'Fleet Manager'), ('finance', 'Finance')], max_length=20)),
                ('widgets', models.JSONField(default=list)),
                ('layout', models.JSONField(default=dict)),
                ('filters', models.JSONField(default=dict)),
                ('is_shared', models.BooleanField(default=False)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('share_expiry', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('revenue', 'Revenue Report'), ('bookings', 'Bookings Report'), ('fleet', 'Fleet Utilization'), ('customer', 'Customer Analytics'), ('payment', 'Payment Analysis'), ('support', 'Support Performance'), ('marketing', 'Marketing ROI'), ('custom', 'Custom Report')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='one_time', max_length=20)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.JSONField(default=list)),
                ('generated_file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('file_size', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_number'], name='analytics_r_report__78f456_idx'), models.Index(fields=['report_type'], name='analytics_r_report__06672b_idx'), models.Index(fields=['next_run'], name='analytics_r_next_ru_559703_idx')],
            },
        ),
    ]
