# Generated by Django 5.2.12 on 2026-03-27 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enquiry_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('aircraft_category', models.CharField(blank=True, choices=[('private_jet', 'Private Jet'), ('cargo', 'Cargo Plane'), ('helicopter', 'Helicopter'), ('special_mission', 'Special Mission'), ('commercial', 'Commercial')], max_length=50)),
                ('departure_airport', models.CharField(blank=True, help_text='IATA code', max_length=3)),
                ('arrival_airport', models.CharField(blank=True, help_text='IATA code', max_length=3)),
                ('preferred_departure_date', models.DateField(blank=True, null=True)),
                ('preferred_return_date', models.DateField(blank=True, null=True)),
                ('flexible_dates', models.BooleanField(default=False)),
                ('passenger_count', models.IntegerField(default=1)),
                ('luggage_count', models.IntegerField(default=0)),
                ('luggage_weight_kg', models.DecimalField(decimal_places=2, default=0, help_text='Total luggage weight in kg', max_digits=10)),
                ('special_luggage', models.TextField(blank=True, help_text='Golf clubs, skis, etc.')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='WiFi, catering, etc.')),
                ('catering_requirements', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('ground_transportation', models.BooleanField(default=False)),
                ('hotel_accommodation', models.BooleanField(default=False)),
                ('pet_travel', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contract_sent', 'Contract Sent'), ('payment_received', 'Payment Received'), ('booked', 'Booked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('contract_sent_at', models.DateTimeField(blank=True, null=True)),
                ('contract_expiry', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('source', models.CharField(default='website', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='fleet.aircraft')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enquiry_number'], name='fleet_enqui_enquiry_33a244_idx'), models.Index(fields=['email', 'status'], name='fleet_enqui_email_3e0c3a_idx'), models.Index(fields=['status', 'created_at'], name='fleet_enqui_status_39f9af_idx')],
            },
        ),
    ]
