# Generated by Django 5.2.12 on 2026-03-29 00:49

import django.core.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_enquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['manufacturer__name', 'model']},
        ),
        migrations.RemoveIndex(
            model_name='aircraft',
            name='fleet_aircr_max_ran_cbfbce_idx',
        ),
        migrations.RemoveIndex(
            model_name='aircraft',
            name='fleet_aircr_hourly__6dfcc3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='aircraftimage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='autopilot',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='avionics_suite',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='catering_charge_per_pax',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='certification_expiry',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='certification_number',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='cleaning_charge_usd',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='daily_rate_usd',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='empty_weight_kg',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='engine_count',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='engine_power',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='featured_until',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='fuel_capacity_l',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='fuel_consumption_lph',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='hourly_rate_usd',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='insurance_expiry',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='interior_color_scheme',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='interior_configuration',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='interior_materials',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='landing_distance_m',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='last_flight_date',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='last_interior_refurbished',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='max_landing_weight_kg',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='max_range_km',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='max_speed_knots',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='max_takeoff_weight_kg',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='minimum_booking_hours',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='monthly_rate_usd',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='next_maintenance_due',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='next_maintenance_type',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='overnight_charge_usd',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='payload_kg',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='service_ceiling_ft',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='takeoff_distance_m',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='terrain_awareness',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='total_cycles',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='traffic_collision_avoidance',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='weather_radar',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='weekly_rate_usd',
        ),
        migrations.RemoveField(
            model_name='aircraftcategory',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='aircraftcategory',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='aircraftcategory',
            name='meta_title',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='baggage_capacity_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Baggage capacity in kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='base_airport',
            field=models.CharField(help_text='IATA code of home base (e.g., JFK, LHR)', max_length=3),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='cabin_height_m',
            field=models.DecimalField(decimal_places=2, help_text='Cabin height in meters', max_digits=4),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='cabin_length_m',
            field=models.DecimalField(decimal_places=2, help_text='Cabin length in meters', max_digits=5),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='cabin_width_m',
            field=models.DecimalField(decimal_places=2, help_text='Cabin width in meters', max_digits=4),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='cargo_capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For cargo aircraft only', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='crew_required',
            field=models.IntegerField(default=2, help_text='Minimum crew required'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='cruise_speed_knots',
            field=models.IntegerField(help_text='Cruising speed in knots'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='current_location',
            field=models.CharField(help_text='IATA code of current location (e.g., JFK, LHR)', max_length=3),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='height_m',
            field=models.DecimalField(decimal_places=2, help_text='Aircraft height in meters', max_digits=5),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='length_m',
            field=models.DecimalField(decimal_places=2, help_text='Aircraft length in meters', max_digits=5),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or special features'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='passenger_capacity',
            field=models.IntegerField(help_text='Maximum number of passengers', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Under Maintenance'), ('chartered', 'Chartered'), ('grounded', 'Grounded')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Main display image for this aircraft', null=True, upload_to='aircraft/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='wingspan_m',
            field=models.DecimalField(decimal_places=2, help_text='Wingspan in meters', max_digits=5),
        ),
        migrations.AlterField(
            model_name='aircraftcategory',
            name='category_type',
            field=models.CharField(choices=[('private_jet', 'Private Jet'), ('cargo', 'Cargo Plane'), ('helicopter', 'Helicopter')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='aircraftcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aircraftcategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='aircraftimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Brief description of the image', max_length=200),
        ),
        migrations.AlterField(
            model_name='aircraftimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Set as main image for gallery'),
        ),
        migrations.AlterField(
            model_name='aircraftimage',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Order in which images appear'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='aircraft_category',
            field=models.CharField(blank=True, choices=[('private_jet', 'Private Jet'), ('cargo', 'Cargo Plane'), ('helicopter', 'Helicopter')], max_length=50),
        ),
    ]
