# Generated by Django 5.2.12 on 2026-03-29 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_aircraft_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='passenger_capacity',
            field=models.IntegerField(help_text='Maximum number of passengers (0 for cargo aircraft)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
