# Generated by Django 5.2.12 on 2026-03-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_aircraft_passenger_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='Number of Reviews'),
        ),
    ]
