# Generated by Django 5.2.12 on 2026-04-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_aircraft_average_rating_aircraft_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='cargo_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cargo weight in kg (for cargo enquiries)', max_digits=10, null=True),
        ),
    ]
