# Generated by Django 5.2.12 on 2026-05-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_enquiry_cargo_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='cabin_height_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cabin height in meters', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='cabin_length_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cabin length in meters', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='cabin_width_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cabin width in meters', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aircraft height in meters', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aircraft length in meters', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='wingspan_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wingspan in meters', max_digits=5, null=True),
        ),
    ]
