# Generated by Django 5.2.12 on 2026-03-24 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent', models.CharField(db_index=True, max_length=100)),
                ('patterns', models.JSONField(default=list, help_text='List of example phrases')),
                ('responses', models.JSONField(default=list, help_text='List of possible responses')),
                ('context', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(default='en', max_length=10)),
                ('confidence_threshold', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('times_used', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['intent'],
                'indexes': [models.Index(fields=['intent', 'is_active'], name='chat_chatbo_intent_002fd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting', 'Waiting for Agent'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('sentiment', models.FloatField(blank=True, help_text='Sentiment score -1 to 1', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('page_url', models.URLField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('satisfaction_feedback', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('estimated_wait_time', models.DurationField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='chat.conversation')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('resolved_issue', models.BooleanField(default=True)),
                ('agent_helpful', models.BooleanField(default=True)),
                ('response_time_satisfied', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('is_agent', models.BooleanField(default=False)),
                ('is_ai', models.BooleanField(default=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System'), ('ai', 'AI Response'), ('typing', 'Typing Indicator')], default='text', max_length=20)),
                ('message', models.TextField()),
                ('html_message', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='chat_attachments/%Y/%m/%d/')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_size', models.IntegerField(default=0)),
                ('attachment_type', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('suggested_responses', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_id'], name='chat_conver_convers_289a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-started_at'], name='chat_conver_user_id_051f13_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'priority'], name='chat_conver_status_e22751_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['agent', 'status'], name='chat_conver_agent_i_a11f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatqueue',
            index=models.Index(fields=['position'], name='chat_chatqu_positio_e077b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatfeedback',
            unique_together={('conversation',)},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='chat_messag_is_read_872c73_idx'),
        ),
    ]
