# Generated by Django 5.2.12 on 2026-04-02 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_aircraft_alter_booking_passenger_count_and_more'),
        ('chat', '0002_alter_conversation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='active_agent_viewing',
            field=models.ForeignKey(blank=True, help_text='Agent currently viewing this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actively_viewing_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent_viewing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['active_agent_viewing'], name='chat_conver_active__f90e6b_idx'),
        ),
    ]
